training : /caa/Homes01/mpeer/workspace-git/write/ssl/datasets/grk50/grk50_5k_patches_christlein.csv
validation :  /caa/Homes01/mpeer/workspace-git/write/ssl/datasets/grk50/grk50_5k_patches_christlein.csv
testing :  /caa/Homes01/mpeer/workspace-git/write/ssl/datasets/grk50/grk50_5k_patches_christlein.csv

logging_group : grk50_ensemble
train_label : cluster

super_fancy_new_name : test

# model_zoo:
#   experiment : ABLATION_MASK_RATIO_FULL_MODEL
#   model : 0.75

model_zoo:
  experiment : ABLATION_EMBEDDING_DIM_FULL_MODEL
  model : 128

finetune_options:
  freeze_backbone : False

log_dir: experiments
logger : wandb

img_size : 32
init_netvlad : False
netvlad_pooling : False

netvlad:
  num_clusters : 32
  random : True

model_options:
  in_dim : -1
  global_pool : False
# 
clip_gradients : 0.25

optimizer_options: 
  optimizer: adamw
  base_lr: 0.0001 
  final_lr: 0.00001
  start_lr : 0
  warmup_epochs : 5
  base_wd: 0.001
  final_wd : 0.000
  start_wd : 0.000
  netvlad_lr_factor : 1
  pca_lr_factor : 1
  layer_decay : 0.9


train_options: 
  epochs: 30
  batch_size: 1024 # 16
  early_stopping : 10
  length_before_new_iter : 256000
  # mixed_precision : True
  margin : 0.1
  sampler_m : 16
  use_best_model : True
  loss : msloss
  loss_a : 2
  loss_b : 40
  loss_base : 0.8
  mining_margin : 0.1
  
eval_options : 
  pca_dim : 512
  num_samples : -1
  apply_pca : False
  only_whitening : True
val_options:
    num_samples : -1

test_batch_size : 1024